### ISSUE TITLE
Option for "Loudness Equalization" does not show up

### ISSUE THREAD

**Issue by KnechtNoobrecht** [Naozumi520/mbp16-bootcamp-Speakers-mod#11]
Hi.
First of all, i appreciate your work and big thumbs up for this project!
I followed your tutorial step by step including the one where you put 3 entries into the registry.
I copied device command from APO configurator -> opened regedit -> searched -> found -> pasted the entries.
However, the option for Loudness Equalization does not show up.
The whole tab isn't even there.
Without this, currently there is much better bass but mediocre mids and highs. Even sounds a bit muffled at times (only mids and highs!).
Any advice?

**Comment by KnechtNoobrecht** [comment]
![image](https://github.com/Naozumi520/mbp-16-bootcamp-speaker-mod/assets/56320300/3db4aed3-30f9-411a-851b-d15f3b6a1699)

![image](https://github.com/Naozumi520/mbp-16-bootcamp-speaker-mod/assets/56320300/16b50a2a-cb29-446a-9625-7b5bff39debd)

**Comment by Naozumi520** [comment]
Hi! I'm sorry to see the option didn't show up for you. Did reboot fix the issue? Cause it need reboot apply the changes. Sorry I have no more advices than that. It's odd that the option not showing up. What version of windows 11 you're now using? I'm using windows 11 and it works well with it.

**Comment by KnechtNoobrecht** [comment]
> Hi! I'm sorry to see the option didn't show up for you. Did reboot fix the issue? Cause it need reboot apply the changes. Sorry I have no more advices than that. It's odd that the option not showing up. What version of windows 11 you're now using? I'm using windows 11 and it works well with it.

I rebooted multiple times and verified the entries persisted. I also tried reinstalling the Apple Audio Driver. I am using Windows 11 Pro 22H2 Build 22621.1928.

**Comment by KnechtNoobrecht** [comment]
> Hi! I'm sorry to see the option didn't show up for you. Did reboot fix the issue? Cause it need reboot apply the changes. Sorry I have no more advices than that. It's odd that the option not showing up. What version of windows 11 you're now using? I'm using windows 11 and it works well with it.

Could you please provide me with your exported registry keys of your speaker device? I hope this will make it work for me.

**Comment by Naozumi520** [comment]
[{f147498d-fbee-4748-bff9-39c625dfda15}.zip](https://github.com/Naozumi520/mbp-16-bootcamp-speaker-mod/files/11981308/f147498d-fbee-4748-bff9-39c625dfda15.zip)
Sorry for the late reply, here is the exported registry keys.

**Comment by KnechtNoobrecht** [comment]
Thank you. I imported the FxProperties keys and now it works. Although i don't hear any difference between it toggled on or off.
