### ISSUE TITLE
现在已经有新的测试驱动了吗

### ISSUE THREAD

**Issue by QiuChenly** [Naozumi520/mbp16-bootcamp-Speakers-mod#7]
一直在关注这个项目的进展

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Naozumi520** [comment]
未來幾星期應該會有了，抱歉久等了。

本人的電腦上個月損壞了(右側硬盤芯片連同供電線路損壞), 雖然能夠維修但同時調試的音效配置文件也沒有了，所有的東西都會重頭再來，幸好有之前的經驗進度也還可以。

另外聽從了一名網友的意見，未來可能還會有解決windows下喇叭爆音的背景程序（就是在背景播放靜音文件，保持聲卡工作）。

**Comment by QiuChenly** [comment]
🙏🏻希望電腦沒事
兄弟還是要註意保護 Mac確實有些脆弱
我還是有一次吃泡麵不小心撒了整個鍵盤的泡面湯 雖然第一時間倒扣流水但還是去更換了鍵盤  3000多人民幣 心痛

**Comment by QiuChenly** [comment]
声卡在Windows下面长时间播放音乐(e.g.  网易云音乐、3A游戏等)有偶尔的爆音（啪的一声）  已排除硬件问题 macOS下工作正常 不知道是不是Windows驱动的问题  有可能能解决这个问题吗

**Comment by Naozumi520** [comment]
目前来看背景播放静音文件 (上面提到的未来会有的背景程序) 能够解决爆音 (保持声卡工作), 但不清楚是不是你指的问题

爆音的问题已经存在已久了, 不论是macOS 还是 Windows, 比较像是硬件问题, 而我研究了后认为macOS用了某种手段来避免了这种问题

macOS 进入 `/System/Library/Audio/Tunings/` 文件夹, 打开任何一款机型文件夹 (这里以我们16吋 `Mac-E1008331FDC96864` 为例), 用编辑器打开里面的`/DSP/Graphs/builtin_speaker_out.dspg`文件, 能清楚的看到以下的注解:

<img width="483" alt="Screenshot 2022-11-16 at 10 09 15 PM" src="https://user-images.githubusercontent.com/52615455/202202453-0b58955c-d9e7-4063-bb65-5123b46cfcf1.png">

看来其中一种手段是播放/停止音效时作出调节, 而我们知道其中最可能出现爆音的情况正正就是播放/停止音效

**Comment by QiuChenly** [comment]
谢谢你的回复与工作！期待新的解决方案😃

**Comment by Naozumi520** [comment]
我想我应该先发布当前的 eq 文件, 毕竟花了太长时间 
硬件爆音解决方案我想我会作为一个拆分项目来开发。

我希望你能够为我测试下新的 eq 文件，然后我再替换到 github 中的主仓库 🙏🏻。由于一直在我的 MacBook 上进行调音工作，我担心扬声器变得不够准确 (扬声器损耗)，无法作为参考。另外我发现有趣的是重新安装bootcamp后旧的 eq 听起来不一样了，这让我担心仅仅使用EQ调音不够准确。

原始bootcamp驱动程序中自动安装的dolby atmos会影响 eq 并限制调整的可能性，安装两个eq也没有意义, 因此新 eq 需要将其删除。我注意到有些人的bootcamp安装驱动的时候dolby atmos没有被自动安装（但它包含在驱动程序中并且我的会自动安装），这就很奇怪了。 如果你的Mac没有安装dolby atmos，请跳至安装 eq 的部分.
这里是将其删除的方法:

在Dolby atmos程序关掉全局应用:
![image](https://user-images.githubusercontent.com/52615455/205484163-0297da53-81d8-428e-8342-a63009badb0f.png)
打开任务管理器服务选项, 禁用DolbyDAXAPI:
![image](https://user-images.githubusercontent.com/52615455/205484170-e899fc65-d394-4a8b-be27-04d60c10783a.png)
找到Dolby atmos应用程序并卸载:
![image](https://user-images.githubusercontent.com/52615455/205484175-8bb8679f-6dac-4ac2-b075-f2f0fc18f2b2.png)
删除 `C:\Windows\System32\dolbyaposvc\PCI_DEV_1803_SUBSYS_1887106B_PCI_SUBSYS_72708086.xml`
![image](https://user-images.githubusercontent.com/52615455/205485705-aa60e9ee-6974-4b83-898f-f7497eb9db59.png)

## 检查Equalizer APO 状态:

![image](https://user-images.githubusercontent.com/52615455/205484180-9c877e18-4dfc-4a8d-b52f-4c1d0bd43b02.png)
![image](https://user-images.githubusercontent.com/52615455/205484191-077a6931-fe39-41a6-97ea-cbd1ccc0005c.png)

## 如果删除dolby atmos后Equalizer APO驱动没有安装到你的扬声器上 (扬声器未选择)，请按照设置重新安装, 如果已经安装, 请跳至安装 eq 的部分:
## **记住不要选择并安装在耳机上**
![image](https://user-images.githubusercontent.com/52615455/205484196-0ae68481-c898-41d7-acda-3bd6bb104c03.png)
![image](https://user-images.githubusercontent.com/52615455/205484207-57b559bc-b71e-4f7b-a7b5-c478727810fe.png)

## 重新启动你的 MacBook, 然后我们将会安装新的 eq:
[MSG1.0_mbp16.zip](https://github.com/Naozumi520/mbp16-bootcamp-Speakers-mod/files/10148325/MSG1.0_mbp16.zip)

下载并解压以上压缩文件，在解压出的文件夹内你会看到两个folder：`config` 和 `ReaPlugs`

1. 拔下耳机并将扬声器音量调低
2. 将 `ReaPlugs` 文件夹复制到 `C:\Program Files\EqualizerAPO\VSTPlugins` 里面
3. 将 `config` 文件夹复制**并替换**到 `C:\Program Files\EqualizerAPO` 里面
4. 播放一些音乐观察效果并调节音量 (我推荐[tsukinimade的無色故に透明](https://www.youtube.com/watch?v=VcxvDmJVECo))😂

测试后请报告问题，谢谢 😃

**Comment by QiuChenly** [comment]
测试后将报告详细数据 谢谢你的工作！😊

**Comment by QiuChenly** [comment]
安装了新发布的版本。

Base：WIndows 11 22H2, 卸载了杜比音效，删除了扬声器配置文件，重新安装了本Repo中提供的声卡驱动程序6.1.7700.3 (未经数字签名)。重新设置了APO驱动到扬声器上。
由于鄙人并不是专业音乐人，只能凭感觉判断。
复制两个文件夹后，有以下效果呈现：

1.低音有抑制，当某些音乐在高音和低音切换时重低音部分有明显的↑↓忽高忽低的压抑感。具体表现为高音立马切换到低音音频时有突然的低音效果，衔接不够自然。其中，重低音播放时对应部分的人声也会被抑制，听起来比较奇怪。（TestMusic https://music.163.com/song?id=448474191&userid=116901232  第15-17秒，46-49秒中间的低音明显的压抑 然后立马切到高音部分）（TestMusic2 https://music.163.com/song?id=34045251&userid=116901232 前48秒）
2.高音部分有抑制 但不明显。
3.相比未启用APO混音：较为完美的重低音效果，但高音收到抑制。

相对上一版本：
1. 整体播放音效变化不大，主要是低音部分有了大幅增强。
2. 总体体验很好。

**Comment by Naozumi520** [comment]
感谢测试！关于频率部分可能出现音量不平衡的情况, 恐怕我对此无能为力。一开始我也注意到了这个情况, 当我把EQ调得太重时会十分明显。我认为这是苹果对 Windows 设置的音量限制 [(一些用户报告高音量音量太高损坏了他们的扬声器)](https://www.notebookcheck.net/Apple-MacBook-Pro-Boot-Camp-Windows-audio-driver-can-damage-speakers.185764.0.html)
同时我需要降低高音并增加低音时, 这会降低整体音量。我的解决方案是使用前置放大器来增加音量，但是副效果是音量不平衡，正如你提到的不同频率整体音量可能不平衡。

**Comment by Naozumi520** [comment]
@QiuChenly 
音量不平衡的情况已在v2.3中修復，請查看！😊

更新: (安裝前請查看README文件中的安裝指南)

**Comment by QiuChenly** [comment]
谢谢你的工作！🍻
