### ISSUE TITLE
Sound worse than before

### ISSUE THREAD

**Issue by crackajack77** [Naozumi520/mbp16-bootcamp-Speakers-mod#8]
So I encountered the thin Boot Camp Windows 10 sound using my 16" MacBook Pro 2019 and thought to give this a try, it actually sounds even worse. Volume is super low, EQ is way to drastic (average lowering of -13 db per band?).

Also, why do I need to use use Dolby Atmos? Not a default Windows 10 program, also proprietory. 

Would not recommend.

**Comment by Naozumi520** [comment]
Well, that's odd, cuz the sound here is definitely better than pure driver output. See [comments here](https://www.reddit.com/r/bootcamp/comments/ltifl0/fix_sound_quality_under_bootcamp_of_macbook_pro/) also giving position feedback.

You mentioned why you need to use Dolby Atmos. Of course, you don't need Dolby Atmos. But virtually all MacBook Pro come with Dolby Atmos installed by default on BootCamp. 

You enter the folder Original_drivers&files in this repo and you can see the drivers [AppleAudio_1887106B](https://github.com/Naozumi520/mbp16-bootcamp-Speakers-mod/tree/main/Original_drivers%26files/AppleAudio_1887106B) copied from the bootcamp installer for Dolby Atmos, which is controlling Dolby Atmos and some minor adjustments. Its EQ is way too thin by default, so I mostly increased the frequency on midrange. So I guess there is something wrong with your bootcamp setup installation, causing Dolby Atmos not to install.

Just simply install by right click and press install on these `.inf` in your downloaded bootcamp folder.
`BootCamp-061-62383/$WinPEDriver$/AppleAudio_1887106B/AppleAudio_1887106B.inf`
`BootCamp-061-62383/$WinPEDriver$/Dolby/swc_aposvc/dax3_swc_aposvc.inf/`
`BootCamp-061-62383/$WinPEDriver$/Dolby/swc_hsa/dax3_swc_hsa.inf`

But before trying it, I suggest you wait until the next EQ comes out. I've noticed that Dolby Atmos is one of the things that causes volume issues and makes the EQ harder to adjust. Therefore, in the next version, Dolby Atmos needs to be removed before installation.
