### ISSUE TITLE
How is the project going && New EQ is now open for test

### ISSUE THREAD

**Issue by Naozumi520** [Naozumi520/mbp16-bootcamp-Speakers-mod#9]
I hope guys seeing this issue can first test the new eq file for me before I replaced the main one in the repo in 🙏🏻. 

Since I've been doing tuning work on my MacBook, I'm concerned that the speakers are becoming inaccurate (speaker loss) to be use as a reference. Also I found it interesting as the old eq doesn't sound the same after reinstalling bootcamp, which makes me worry that just using the EQ for tuning isn't accurate enough (It used to be opened for repairs as well). Everyone's feedback is valuable here.

I know the new EQ took too long, sorry about that. My macbook once broke and I had to start over as all the data were gone after repair (broken ssd chips and circuits), but luckily the new eq worked much better for me.
In meantime the hardware pop solution I think I'll develop as a split project.

<details>
<summary>Click me if you hope to install the new EQ **experimental**</summary>&nbsp;
   
   
The automatically installed dolby atmos in the original bootcamp driver affects the eq and limits the tuning possibilities, there is no point in installing two eqs, in order to install the new eq dolby atmos needs to be removed. I've noticed that dolby atmos isn't automatically installed when some people's bootcamp installs the driver (but it's included in the driver and mine does), which is weird. If your Mac does not have dolby atmos installed, skip to the section on installing eq.
Here's how to remove it:

Turn off the global application in the Dolby atmos program:
![image](https://user-images.githubusercontent.com/52615455/205484163-0297da53-81d8-428e-8342-a63009badb0f.png)
Open Task Manager Services Options, disable DolbyDAXAPI:
![image](https://user-images.githubusercontent.com/52615455/205484170-e899fc65-d394-4a8b-be27-04d60c10783a.png)
Find the Dolby atmos app and uninstall it:
![image](https://user-images.githubusercontent.com/52615455/205484175-8bb8679f-6dac-4ac2-b075-f2f0fc18f2b2.png)
delete `C:\Windows\System32\dolbyaposvc\PCI_DEV_1803_SUBSYS_1887106B_PCI_SUBSYS_72708086.xml`
![image](https://user-images.githubusercontent.com/52615455/205485705-aa60e9ee-6974-4b83-898f-f7497eb9db59.png)

## Check the Equalizer APO status:

![image](https://user-images.githubusercontent.com/52615455/205484180-9c877e18-4dfc-4a8d-b52f-4c1d0bd43b02.png)
![image](https://user-images.githubusercontent.com/52615455/205484191-077a6931-fe39-41a6-97ea-cbd1ccc0005c.png)

## **Remember not to select and install on headset**
![image](https://user-images.githubusercontent.com/52615455/205484196-0ae68481-c898-41d7-acda-3bd6bb104c03.png)
![image](https://user-images.githubusercontent.com/52615455/205484207-57b559bc-b71e-4f7b-a7b5-c478727810fe.png)

## Reboot your MacBook, and we'll install the new eq:
[MSG1.0_mbp16.zip](https://github.com/Naozumi520/mbp16-bootcamp-Speakers-mod/files/10148325/MSG1.0_mbp16.zip)

Download and unzip the above compressed file, you will see two folders in the unzipped folder: `config` and `ReaPlugs`

1. Unplug the headphones and turn the speaker volume down
2. Copy the `ReaPlugs` folder to `C:\Program Files\EqualizerAPO\VSTPlugins`
3. Copy **and replace** the `config` folder to `C:\Program Files\EqualizerAPO`
4. Play some music to observe the effect and adjust the volume (I recommend [無色故に透明](https://www.youtube.com/watch?v=VcxvDmJVECo))😂
Please report issues after testing, thanks 😃
</details>

**Comment by bananakid** [comment]
Open beta is a great idea! Don't worry that your speakers were altered during repairs, it's really unlikely thing to happen. I'm 100% sure your MBP's speakers are just as good as factory ones (as far as you don't hear any obvious defects).

P.S. While I enjoyed the example track you linked it may be a good idea to double-check equalizer preset result using tracks that are used more often like [Money for Nothing](https://www.youtube.com/watch?v=wTP2RUD_cL0), [Hotel California](https://youtu.be/BciS5krYL80), [Sympathy for the Devil (Neptunes Radio Edit)](https://www.youtube.com/watch?v=DOVVN-9qbwc). Nailing output of such complex tracks (in comparison to macOS) may provide a better overall output (in Boot Camp).

**Comment by muffinized** [comment]
Helloooooo
I like the idea of a beta xD I've seen some similar problems with the speakers, as on every reboot it tends to sound a little different, with frequent internal buzzing. Also, the wait is acceptable, thank you for helping us improve the speaker quality of Boot Camp :D (now I just need to fix cpu voltage curve ! )

**Comment by muffinized** [comment]
I do think the bass is causing the degradation as i don't think the subs are being used at all (I feel no vibration at all)

**Comment by Naozumi520** [comment]
Actually, I've been interested in this project recently:
https://github.com/chadmed/asahi-audio
The same goes for projects here, but this guy has more knowledge and have more specialized equipment than I do. I tried porting this eq (orginal for linux, macbook pro 14 2021) to bootcamp and it sounds great (still if the volume can be unbalanced when the bass and treble of the song are too high, same as this project). The thing I'm just worried about is idk can I take this project and mention that I've used his file. I don't know much about [MIT License](https://github.com/chadmed/asahi-audio/blob/main/LICENSE).

**Comment by Naozumi520** [comment]
> now I just need to fix cpu voltage curve ! 

But talking about cpu voltage, isn't the voltage on bootcamp cannot be changed? I've tried only limits the cpu watts only. lol
I did hope that we'll be able to adjust the cpu voltage :(

> I feel no vibration at all

It normal to feel no vibration when playing songs with bass lol. The mbp16 inch used the Force-Canceling Drivers to avoid the laptop vibrate when playing music. EQ helps to increase the bass just like macOS, and I'm 100% sure that the 4 woofers has mapped on bootcamp as well. If only tweeter were mapped then it will sounds way terrible.

**Comment by muffinized** [comment]
> talking about cpu voltage, isn't the voltage on bootcamp cannot be changed? I've tried only limits the cpu watts only. lol I did hope that we'll be able to adjust the cpu voltage :(

i use QuickCPU which is p cool, I found using clock modulation & energy policy helps w battery but not perf.... However, I'm sure there's a weird setting _somewhere_ that can fix voltage (I'll do some research and update you when I find a solution) 
> EQ helps to increase the bass just like macOS, and I'm 100% sure that the 4 woofers has mapped on bootcamp as well.

Sorry for the misinformation xD It's such a shame that the woofers are mapped the same as tweeters so we can't get rid of the artifacts created by the tweeters :C
EDIT : I MANAGED TO MITIGATE THE ARTIFACTS :D by making sure the only part which is red (part which is gained) is 50-100 hz  because otherwise there's weird popping / buzzing from the tweeters 
![image](https://user-images.githubusercontent.com/66737626/208722529-5127eddf-42a3-4590-84c4-a6d08444f0de.png)

**Comment by muffinized** [comment]
Btw if you don't mind, can you please send this menu in this thread? I don't have RLOW, LLOW, RHIGH, LHIGH channels
![image](https://user-images.githubusercontent.com/66737626/208721952-bad45920-2b66-4301-ab15-f7fea2b03a04.png)

**Comment by Naozumi520** [comment]
![image](https://user-images.githubusercontent.com/52615455/208723385-6dbd8b20-6ba2-4a31-b6da-b05b8554e768.png)
It's the same, as you mention the woofers are mapped the same as tweeters, we have only 2 channels on bootcamp - L and R channels, and this is what makes it difficult cuz we can't adjust specifically for the woofers or tweeters.

And about porting the linux EQ based on MIT License, I'm sure that I could include the files as far as including the credit of the author. Add my discord Naozumi#0233 if you want to test so I can send it there! 👍

**Comment by muffinized** [comment]
你好可愛meow

**Comment by Naozumi520** [comment]
> 你好可愛meow

?
